#!/bin/sh

configURI=https://www.runescape.com/k=5/l=\$\(Language:0\)/jav_config.ws
flags=""

for x in "$@"; do
	case "$x" in
		-*) flags="$flags $x" ;;
		*)  configURI=$x ;;
	esac
done

export PULSE_PROP_OVERRIDE="application.name='RuneScape' application.icon_name='runescape' media.role='game'"
export SDL_VIDEO_X11_WMCLASS="RuneScape"
export MESA_GL_VERSION_OVERRIDE=3.0
nxtlauncher --configURI $configURI$flags

